#!/bin/bash

CONSOLE_CONFIG_PATH="/boot/config.txt"
UI_CONFIG_PATH="/boot/firmware/config.txt"
SELECTED_PATH_FILE="/tmp/config.tmp"
SEARCHED_TEXT="DO NOT EDIT THIS FILE"
IS_FILE_MOVED=0 

if [ -f "$CONSOLE_CONFIG_PATH" ]; then
    echo "File $CONSOLE_CONFIG_PATH was found"
    out=$(cat "$CONSOLE_CONFIG_PATH" | grep "$SEARCHED_TEXT")
    if [[ "$out" == *"$SEARCHED_TEXT"* ]]; then
	    IS_FILE_MOVED=1
    fi
else
    echo "The configuration file at path $CONSOLE_CONFIG_PATH does not exist."
    echo "Exiting the script.."
    exit 1
fi

touch /tmp/config_path.tmp

if [[ "$IS_FILE_MOVED" -eq 1 ]]; then
    echo -n "$UI_CONFIG_PATH" > "$SELECTED_PATH_FILE"
else
    echo -n "$CONSOLE_CONFIG_PATH" > "$SELECTED_PATH_FILE"
fi
