#!/bin/bash

CONSOLE_CONFIG_PATH="/home/daniel/Projects/radio/setup/scripts/config.txt"
UI_CONFIG_PATH="/boot/firmware/config.txt"
SELECTED_CONFIG="$CONSOLE_CONFIG_PATH"
SEARCHED_TEXT="DO NOT EDIT THIS FILE"

echo " --> Find the which config file can we edit"
if [ -f "$CONSOLE_CONFIG_PATH" ]; then
    out=$(cat "$CONSOLE_CONFIG_PATH" | grep "$SEARCHED_TEXT")
    if [[ "$out" == *"$SEARCHED_TEXT"* ]]; then
	    SELECTED_CONFIG="$UI_CONFIG_PATH"
    fi
else
    echo "The configuration file at path $CONSOLE_CONFIG_PATH does not exist."
    echo "Exiting the script.."
    exit 1
fi

echo "Selected config is: $SELECTED_CONFIG"

echo " --> Uncomment 'dtparam=i2s=on'"
sed -i 's/^#\(dtparam=i2s=on\)/\1/' "$SELECTED_CONFIG"

echo " --> Comment the line 'dtparam=audio=on'"
sed -i 's/^\(dtparam=audio=on\)/#\1/' "$SELECTED_CONFIG"

echo " --> Add the line 'dtoverlay=iqaudio-dacplus,unmute_amp'"
sed -i '$a dtoverlay=iqaudio-dacplus,unmute_amp' "$SELECTED_CONFIG"

echo " --> Append ',noaudio' to 'dtoverlay=vc4-kms-v3d'"
sed -i 's/^\(dtoverlay=vc4-kms-v3d\)\(.*\)/\1,noaudio\2/' "$SELECTED_CONFIG"